steps:
- name: 'bash'
  args: ['echo', 'Hello world!']
logsBucket: 'lunar-abbey-385508_cloudbuild'
steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - compute
      - instances
      - create
      - my-instance-akl1
      - '--zone=us-central1-a'
      - '--image=pythonserver-10'
      - '--machine-type=n1-standard-1'
  - name: gcr.io/cloud-builders/gcloud
    args:
      - compute
      - ssh
      - my-instance-akl1
      - '--zone=us-central1-a'
      - >-
        --command=sudo apt-get update && sudo apt-get install -y nginx && echo
        "Hello from Cloud Build" | sudo tee /var/www/html/index.html
        
# steps:
#   - name: 'gcr.io/cloud-builders/gcloud'
#     args: ['compute', 'instances', 'stop', 'my-instance-akl', '--zone=us-central1-a']
        
  - name: gcr.io/cloud-builders/gcloud
    args:
      - compute
      - images
      - create
      - my-image-akl1-new
      - '--source-disk=my-instance-akl1'
      - '--source-disk-zone=us-central1-a'
  - name: gcr.io/cloud-builders/gcloud
    args:
      - compute
      - instances
      - delete
      - my-instance-akl1
      - '--zone=us-central1-a'  
      - '--quiet' 
