steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - compute
      - instances
      - create
      - my-instance
      - '--zone=us-central1-a'
      - '--image=debian-9'
      - '--machine-type=n1-standard-1'
  - name: gcr.io/cloud-builders/gcloud
    args:
      - compute
      - ssh
      - my-instance
      - '--zone=us-central1-a'
      - >-
        --command=sudo apt-get update && sudo apt-get install -y nginx && echo
        "Hello from Cloud Build" | sudo tee /var/www/html/index.html
  - name: gcr.io/cloud-builders/gcloud
    args:
      - compute
      - images
      - create
      - my-image
      - '--source-disk=my-instance'
      - '--source-disk-zone=us-central1-a'
  - name: gcr.io/cloud-builders/gcloud
    args:
      - compute
      - instances
      - delete
      - my-instance
      - '--zone=us-central1-a' 
      - '--quiet' 
