steps: 
- name: 'bash'  
  args: ['echo', 'Hello world!'] 
logsBucket: 'lunar-abbey-385508_cloudbuild'
steps:

  # Set the default project ID
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['config', 'set', 'project', 'lunar-abbey-385508']
#   - name: gcr.io/cloud-builders/gcloud
#     args:
#       - compute
#       - instances
#       - create
#       - my-instance-akl1
#       - '--zone=us-central1-a'
#       - '--image=ak-custom-img'
#       - '--machine-type=n1-standard-1'
#   - name: gcr.io/cloud-builders/gcloud
#     args:
#       - compute
#       - ssh
#       - my-instance-akl1
#       - '--zone=us-central1-a'
#       - >-
#         --command=sudo apt-get update && sudo apt-get install -y nginx && echo
#         "Hello from Cloud Build" | sudo tee /var/www/html/index.html
        
# # steps:
#   - name: 'gcr.io/cloud-builders/gcloud'
#     args: ['compute', 'instances', 'stop', 'my-instance-akl1', '--zone=us-central1-a']
        

      

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['compute', 'instance-templates', 'create', 'newinstanvetm1',
         '--source-instance=my-instance-akl1',
         '--source-instance-zone=us-central1-a',
        # '--configure-disk=device-name=my-instance-akl1,instantiate-from=source-image,auto-delete=true']
         '-–configure-disk=device-name=my-instance-akl1,instantiate-from=projects/lunar-abbey-385508//zones/us-central1-a/instances/my-instance-akl1,auto-delete=true']
  - name: gcr.io/cloud-builders/gcloud
    args:
      - compute
      - instances
      - delete
      - my-instance-akl1
      - '--zone=us-central1-a'  
      - '--quiet' 
